//REDUX ACTION TYPES
export const ADD_MOVIE_DATA = 'ADD_MOVIE_DATA';
export const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES';
export const REMOVE_MOVIE_FROM_FAVORITES = 'REMOVE_MOVIE_FROM_FAVORITES';
