//REDUX ACTION TYPES

export const ADD_MOVIE_DATA_REQUEST = 'ADD_MOVIE_DATA_REQUEST';
export const ADD_MOVIE_DATA_SUCCESS = 'ADD_MOVIE_DATA_SUCCESS';
export const ADD_MOVIE_DATA_FAIL = 'ADD_MOVIE_DATA_FAIL';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
